# Generated by Django 4.2.7 on 2025-09-16 09:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Registration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "registration_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "fee_code",
                    models.CharField(
                        blank=True, db_index=True, max_length=20, null=True, unique=True
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                (
                    "email",
                    models.EmailField(
                        db_index=True,
                        max_length=254,
                        validators=[django.core.validators.EmailValidator()],
                    ),
                ),
                ("phone", models.CharField(max_length=20)),
                ("institution", models.CharField(max_length=200)),
                ("country", models.CharField(max_length=100)),
                (
                    "location",
                    models.CharField(
                        choices=[
                            ("abroad", "Registration from Abroad"),
                            ("algeria", "Registration from Algeria"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "registration_type",
                    models.CharField(
                        choices=[
                            ("full", "Full Registration"),
                            ("student", "Student Registration"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "registration_period",
                    models.CharField(
                        choices=[
                            ("early", "Early Registration"),
                            ("normal", "Normal Registration"),
                            ("late", "Late Registration"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "registration_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("tutorial_full_day", models.BooleanField(default=False)),
                ("tutorial_period", models.BooleanField(default=False)),
                ("welcome_dinner", models.BooleanField(default=False)),
                ("dinner", models.BooleanField(default=False)),
                ("gala_dinner", models.BooleanField(default=False)),
                (
                    "menu_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("meat", "Meat Menu"),
                            ("fish", "Fish Menu"),
                            ("vegetarian", "Vegetarian Menu"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("social_program", models.BooleanField(default=False)),
                (
                    "room_type",
                    models.CharField(
                        blank=True,
                        choices=[("single", "Single Room"), ("double", "Double Room")],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "number_of_nights",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("card", "Credit/Debit Card"),
                            ("ccp", "CCP"),
                            ("transfer", "Bank Transfer"),
                            ("stripe", "Stripe Payment"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("currency", models.CharField(default="EUR", max_length=3)),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "payment_reference",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "stripe_payment_intent",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("special_requirements", models.TextField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["email", "payment_status"],
                        name="registratio_email_26c6e7_idx",
                    ),
                    models.Index(
                        fields=["registration_period", "registration_type"],
                        name="registratio_registr_2b6f64_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PaymentTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(max_length=3)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        max_length=20,
                    ),
                ),
                ("payment_method", models.CharField(max_length=50)),
                ("gateway_response", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "registration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="registration.registration",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AccompanyingPerson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("gala_dinner", models.BooleanField(default=False)),
                ("social_program", models.BooleanField(default=False)),
                (
                    "menu_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("meat", "Meat Menu"),
                            ("fish", "Fish Menu"),
                            ("vegetarian", "Vegetarian Menu"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "registration",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accompanying_person",
                        to="registration.registration",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Paper",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("paper_number", models.CharField(max_length=50)),
                ("title", models.CharField(blank=True, max_length=200, null=True)),
                ("is_additional", models.BooleanField(default=False)),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "registration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="papers",
                        to="registration.registration",
                    ),
                ),
            ],
            options={
                "ordering": ["added_at"],
                "unique_together": {("registration", "paper_number")},
            },
        ),
    ]
