# Generated by Django 4.2.7 on 2025-09-27 00:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="accompanyingperson",
            old_name="social_program",
            new_name="dinner",
        ),
        migrations.AddField(
            model_name="accompanyingperson",
            name="lunch_16",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="accompanyingperson",
            name="lunch_17",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="accompanyingperson",
            name="national_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="accompanyingperson",
            name="welcome_dinner",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="accompanyingperson",
            name="welcome_lunch",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="registration",
            name="accommodation_timing",
            field=models.CharField(
                blank=True,
                choices=[
                    ("before", "Night before presentation"),
                    ("presentation", "Night of presentation"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="registration",
            name="lunch",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="registration",
            name="national_id",
            field=models.CharField(
                blank=True,
                help_text="National ID or Passport Number",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="registration",
            name="paper_count",
            field=models.IntegerField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AlterField(
            model_name="registration",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("card", "Credit/Debit Card"),
                    ("transfer", "Bank Transfer"),
                    ("stripe", "Stripe Payment"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="registration",
            name="registration_type",
            field=models.CharField(
                choices=[
                    ("full", "Full Registration"),
                    ("student", "Student Registration"),
                    ("visitor", "Visitor Registration"),
                ],
                max_length=10,
            ),
        ),
        migrations.AddIndex(
            model_name="registration",
            index=models.Index(
                fields=["national_id"], name="registratio_nationa_5e9e05_idx"
            ),
        ),
    ]
