# Generated by Django 4.2.7 on 2025-09-27 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "registration",
            "0002_rename_social_program_accompanyingperson_dinner_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="accompanyingperson",
            name="dinner_menu",
            field=models.CharField(
                blank=True,
                choices=[
                    ("meat", "Meat Menu"),
                    ("fish", "Fish Menu"),
                    ("vegetarian", "Vegetarian Menu"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="accompanyingperson",
            name="gala_dinner_menu",
            field=models.CharField(
                blank=True,
                choices=[
                    ("meat", "Meat Menu"),
                    ("fish", "Fish Menu"),
                    ("vegetarian", "Vegetarian Menu"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="accompanyingperson",
            name="welcome_dinner_menu",
            field=models.CharField(
                blank=True,
                choices=[
                    ("meat", "Meat Menu"),
                    ("fish", "Fish Menu"),
                    ("vegetarian", "Vegetarian Menu"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="registration",
            name="dinner_menu",
            field=models.CharField(
                blank=True,
                choices=[
                    ("meat", "Meat Menu"),
                    ("fish", "Fish Menu"),
                    ("vegetarian", "Vegetarian Menu"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="registration",
            name="gala_dinner_menu",
            field=models.CharField(
                blank=True,
                choices=[
                    ("meat", "Meat Menu"),
                    ("fish", "Fish Menu"),
                    ("vegetarian", "Vegetarian Menu"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="registration",
            name="welcome_dinner_menu",
            field=models.CharField(
                blank=True,
                choices=[
                    ("meat", "Meat Menu"),
                    ("fish", "Fish Menu"),
                    ("vegetarian", "Vegetarian Menu"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="accompanyingperson",
            name="menu_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("meat", "Meat Menu"),
                    ("fish", "Fish Menu"),
                    ("vegetarian", "Vegetarian Menu"),
                ],
                help_text="Legacy field - use individual dinner menu fields instead",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="registration",
            name="menu_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("meat", "Meat Menu"),
                    ("fish", "Fish Menu"),
                    ("vegetarian", "Vegetarian Menu"),
                ],
                help_text="Legacy field - use individual dinner menu fields instead",
                max_length=20,
                null=True,
            ),
        ),
    ]
