# Generated by Django 4.2.7 on 2025-09-28 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0003_accompanyingperson_dinner_menu_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="accompanyingperson",
            name="menu_type",
        ),
        migrations.RemoveField(
            model_name="accompanyingperson",
            name="welcome_lunch",
        ),
        migrations.RemoveField(
            model_name="registration",
            name="accommodation_timing",
        ),
        migrations.RemoveField(
            model_name="registration",
            name="menu_type",
        ),
        migrations.AddField(
            model_name="accompanyingperson",
            name="lunch_18",
            field=models.BooleanField(default=False, help_text="Lunch - December 18th"),
        ),
        migrations.AddField(
            model_name="registration",
            name="check_in_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="registration",
            name="check_out_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="accompanyingperson",
            name="lunch_16",
            field=models.BooleanField(default=False, help_text="Lunch - December 16th"),
        ),
        migrations.AlterField(
            model_name="accompanyingperson",
            name="lunch_17",
            field=models.BooleanField(default=False, help_text="Lunch - December 17th"),
        ),
        migrations.AlterField(
            model_name="registration",
            name="registration_type",
            field=models.CharField(
                choices=[
                    ("full", "Full Registration"),
                    ("student", "Student Registration"),
                    ("without_paper", "Registration without paper"),
                ],
                max_length=15,
            ),
        ),
    ]
